### ISSUE TITLE
Miscellaneous fixes

### ISSUE THREAD

**Issue by piccolazucca** [rudigernreich/ruditheme#64]
- sidebar: 
    - ~~add social media menu~~
    - ~~newsletter sign-up formatting on black background~~
- product page:
    - ~~"you might also like" images not loading~~ 
    - ~~cart-info too much space on left (`padding-right: 3%`)~~
    - ~~"you might also like" i set 4 item cap~~
- pages 
    - ~~layout on desktop: content cut off by breadcrumb title~~
    - ~~layout on mobile: content width too narrow~~
    - ~~space on bottom of page~~
    - ~~maybe add border underneath header on mobile?~~
    - ~~format content of all pages correctly and consistently (does it make sense to make the h2 titles the same as the page header title?)~~
- collection page:
    - ~~re-upload all images as .png to prevent quality loss~~
    - ~~clicking on collaborator leads to different locations~~
    - ~~clicking on a new collection, all products doesn't show anymore~~
    - ~~change name of accessories~~
- cart page:
    - ~~continue shopping button in empty cart should be vertically aligned~~
    - ~~add a continue shopping button (does this make sense? issue would be resolved with an ajax cart)~~ --> added a left arrow

**Comment by milenazuccarelli** [comment]
See commit: [d295218](https://github.com/rudigernreich/ruditheme/commit/d295218c92475735fd7d9198b0d89e13e2e9fc91)
